#!/usr/bin/env node
/**
 * 5bit CLI — init, gen-types, start, status
 * ===========================================
 * npx fivebit init       → creates fivebit.config.json
 * npx fivebit gen-types  → generates TypeScript types
 * npx fivebit start      → docker compose up
 * npx fivebit status     → health check
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const CONFIG_FILE = 'fivebit.config.json';
const DEFAULT_CONFIG = {
  collections: {
    users: { fields: ['name', 'email', 'balance'] },
    posts: { fields: ['title', 'body', 'author_id'] },
    products: { fields: ['name', 'price', 'stock'] },
  },
};

function init() {
  if (fs.existsSync(CONFIG_FILE)) {
    console.log(`${CONFIG_FILE} already exists.`);
    return;
  }
  fs.writeFileSync(CONFIG_FILE, JSON.stringify(DEFAULT_CONFIG, null, 2));
  console.log(`✓ Created ${CONFIG_FILE}`);
  console.log(`  Edit it to define your collections and fields.`);
}

function genTypes() {
  if (!fs.existsSync(CONFIG_FILE)) {
    console.log(`Run 'fivebit init' first.`);
    process.exit(1);
  }
  const config = JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf-8'));
  let output = `// Auto-generated by fivebit gen-types — do not edit\n\n`;

  for (const [name, spec] of Object.entries(config.collections)) {
    const typeName = name.charAt(0).toUpperCase() + name.slice(1);
    const fields = spec.fields.map(f => `  ${f}: ${f.includes('name') || f.includes('email') || f.includes('title') || f.includes('body') ? 'string' : 'number'};`).join('\n');
    output += `export interface ${typeName} {\n${fields}\n  _id: number;\n  _hash: string;\n}\n\n`;
  }

  const outFile = 'fivebit.d.ts';
  fs.writeFileSync(outFile, output);
  console.log(`✓ Generated ${outFile}`);
}

function start() {
  console.log('Starting 5bit...');
  try {
    execSync('docker compose up', { stdio: 'inherit', cwd: findProjectRoot() });
  } catch {
    console.log('Docker not available — start manually:');
    console.log('  python3 fivebit/api/server.py --port 8080');
  }
}

function status() {
  const urls = ['http://localhost:8080/health', 'http://localhost:8080/records?limit=1'];
  for (const url of urls) {
    try {
      const http = require('http');
      const req = http.get(url, (res) => {
        console.log(`  ${url} → ${res.statusCode}`);
      });
      req.on('error', () => console.log(`  ${url} → ✗ down`));
      req.setTimeout(2000, () => { req.destroy(); console.log(`  ${url} → ✗ timeout`); });
    } catch {
      console.log(`  ${url} → ✗ error`);
    }
  }
  // Wait for responses
  setTimeout(() => {}, 2500);
}

function findProjectRoot() {
  let dir = process.cwd();
  while (dir !== '/') {
    if (fs.existsSync(path.join(dir, 'docker-compose.yml'))) return dir;
    dir = path.dirname(dir);
  }
  return process.cwd();
}

// ── Main ────────────────────────────────────────────────────────────

const cmd = process.argv[2] || 'help';
switch (cmd) {
  case 'init': init(); break;
  case 'gen-types': genTypes(); break;
  case 'start': start(); break;
  case 'status': status(); break;
  default:
    console.log(`5bit CLI — v0.1.0\n`);
    console.log(`  fivebit init        Create fivebit.config.json`);
    console.log(`  fivebit gen-types   Generate TypeScript types`);
    console.log(`  fivebit start       Start with Docker Compose`);
    console.log(`  fivebit status      Health check`);
}
